# docker-compose.yml

services:
  app:
    build: .
    container_name: complaint_service

    # bind host port 8000 to container port 8000
    ports:
      - "8000:8000"

    # load environment variables from .env
    env_file:
      - .env

    # mount project code into container
    volumes:
      - ./:/app
      # named volume for SQLite data storage
      - db_data:/app/data
  n8n:
    image: n8nio/n8n:1.101.1
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - API_URL=${API_URL}
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  db_data:
  n8n_data: