# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Type check (mypy)
        run: mypy src

      - name: Lint (flake8)
        run: flake8 src

      - name: Format check (black)
        run: black --check .

      - name: Imports check (isort)
        run: isort --check-only .

      - name: Run tests
        run: pytest --cov=src
